version: '3.8'

services:
  daily-rem:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    restart: always